import os
import pandas as pd
import numpy as np
from src.utils.config_loader import load_config, logger
from src.recommendation.recommender import calculate_opportunity_score

def compile_markdown_report(df_funding, df_gov, state_index, config):
    """Compiles a beautiful markdown executive report summarizing the Indian startup ecosystem."""
    logger.info("Compiling markdown report...")
    
    # 1. Gather macro KPIs
    total_funding_usd = df_funding["Funding_Amount_USD"].sum()
    total_deals = df_funding.shape[0]
    total_registered = df_gov["Count"].sum()
    top_funded_company = df_funding.sort_values("Funding_Amount_USD", ascending=False).iloc[0]
    
    top_sector_gov = df_gov.groupby("Standard_Industry")["Count"].sum().sort_values(ascending=False).index[0]
    top_sector_fund = df_funding.groupby("Standard_Industry")["Funding_Amount_USD"].sum().sort_values(ascending=False).index[0]
    
    # 2. Build report sections
    report_md = f"""# Executive Intelligence Brief: State of the Indian Startup Ecosystem (2026)
**Prepared for:** Entrepeneurs, Venture Capitalists, and Ecosystem Policy Makers  
**Generated by:** Indian Startup Intelligence Engine  
**Release Date:** May 2026  

---

## 1. Executive Summary

The Indian startup ecosystem continues to represent one of the world's most dynamic growth engines. Integrating micro venture funding data with macro-level government registrations reveals a robust, resilient system traversing a structural shift from cash-burn consumer retail models to high-growth, technology-driven sectors like AI, FinTech, and CleanTech. 

This intelligence brief compiles empirical observations to outline sector opportunities, assess regional densities, project future trajectories, and offer actionable strategic recommendations.

---

## 2. Key Ecosystem Performance Indicators (KPIs)

Below is a summary of the macro registrations and private venture funding metrics aggregated across the ecosystem database:

| Indicator Metric | Aggregated Value | Details & Significance |
| :--- | :--- | :--- |
| **Total Registered Startups** | {total_registered:,} | Registered under DPIIT and state portals (2016 - 2025) |
| **Total Private VC Funding Raised** | ${total_funding_usd / 1e9:.2f} Billion | Total venture capital deployed across private deals |
| **Total Deployed VC Deals** | {total_deals} | Standard high-growth funding transactions documented |
| **Largest Venture Deal** | ${top_funded_company['Funding_Amount_USD']/1e6:.1f} Million | Raised by **{top_funded_company['Company']}** in {top_funded_company['Year']} ({top_funded_company['City']}) |
| **Dominant Sector (by Count)** | {top_sector_gov} | Leading standard sector in macro government registrations |
| **Dominant Sector (by Capital)** | {top_sector_fund} | Leading standard sector in total venture capital attracted |

---

## 3. State Development & Regional Index Rankings

Based on our custom **State Development Index (SDI)**, which incorporates total DPIIT startup registration volume weighted with YoY registration velocity, here are the top 10 states leading entrepreneurship in India:

| Rank | State Name | Total Registered Startups | Growth Velocity Score | State Startup Index Score (0-100) |
| :---: | :--- | :---: | :---: | :---: |
"""
    
    for idx, row in state_index.head(10).iterrows():
        report_md += f"| {idx+1} | **{row['State']}** | {row['Total_Startups']:,} | {row['Growth_Score']:.1f} | **{row['State_Startup_Index']:.1f}** |\n"
        
    report_md += """
---

## 4. Sector Opportunity Assessment

Using our multi-dimensional opportunity matrix, we evaluated three of India's prominent high-growth sectors:

"""
    
    for sector in ["AI & DeepTech", "FinTech", "CleanTech & Green Energy"]:
        opp = calculate_opportunity_score(sector, df_funding, df_gov, config)
        metrics = opp["metrics"]
        
        report_md += f"""### {sector}
- **Sector Opportunity Score:** **{opp['opportunity_score']}/100**
- **DPIIT Registration YoY Velocity:** {metrics['registration_growth']}%
- **Public Sentiment Trend:** {metrics['sentiment']} (Score: {metrics['sentiment_score']})
- **Ecosystem Registry Share:** {metrics['startup_density_pct']}% of registrations
"""
        
    report_md += """
---

## 5. Strategic Recommendations

Based on empirical models and market analysis, we advise the following core strategies:

### 💡 For Entrepreneurs
1. **Target Capital-Efficient B2B SaaS:** SaaS & Enterprise sectors exhibit lower competition risk and higher survival scores.
2. **Leverage State Grants:** Startups located in Uttar Pradesh, Karnataka, and Maharashtra should actively apply for local PoC grants (up to INR 50 Lakhs) to limit early dilution.
3. **Build EV-Adjacent Products:** Given the clean tech push and EV logistics demand, building ancillary technologies offers high success probabilities.

### 💰 For Venture Capitalists
1. **Look Beyond Bangalore:** City clustering shows Gurgaon, Hyderabad, and Noida are rapidly ascending as high-yield hubs with lower talent costs.
2. **Back Regulatory-Resilient FinTechs:** RBI regulatory shifts indicate backing startups focusing on compliance tech and secure rural lending will mitigate portfolios risk.

### 🏛️ For Policy Makers
1. **Incentivize Livelihood Agrotech:** Encourage rural agribusiness hubs under the ASPIRE scheme to optimize food supply chains.
2. **Establish State Incubation Nodes:** Expand world-class incubators in East and Central regions to bridge the startup density gap.
"""
    
    # 3. Save report
    reports_dir = config["resolved_paths"]["reports_dir"]
    report_path = os.path.join(reports_dir, "state_of_startup_ecosystem_2026.md")
    
    with open(report_path, "w", encoding="utf-8") as f:
        f.write(report_md)
        
    logger.info(f"Markdown report compiled and saved to {report_path}")
    return report_path

def generate_report():
    """Pipeline entry to generate the state of the ecosystem markdown report."""
    config = load_config()
    proc_funding = pd.read_csv(os.path.join(config["resolved_paths"]["processed_data_dir"], "processed_funding.csv"))
    proc_gov = pd.read_csv(os.path.join(config["resolved_paths"]["processed_data_dir"], "processed_gov.csv"))
    state_index = pd.read_csv(os.path.join(config["resolved_paths"]["reports_dir"], "state_development_index.csv"))
    
    report_path = compile_markdown_report(proc_funding, proc_gov, state_index, config)
    return report_path

if __name__ == "__main__":
    path = generate_report()
    print("Report compiled successfully at:", path)
